#!/bin/bash
CP=$(./gradlew -q printCp 2>/dev/null | grep '^CP=' | sed 's/^CP=//')
echo "CPLEN=${#CP}"
echo "$CP" | tr ':' '\n' | grep -iE 'minecraft|fabric-(item-group|key|networking|lifecycle|events)' | head -30
p(){ echo "== $1 | $2"; javap -cp "$CP" "$1" 2>&1 | grep -E "$2" | head -50; }
p net.minecraft.world.item.Item 'use\(|Properties|onUseTick|getUseDuration|getUseAnimation|isBarVisible|getBarWidth|getBarColor|getName\(|inventoryTick|isFoil|Item\('
p 'net.minecraft.world.item.Item$Properties' 'setId|stacksTo|durability|component'
p net.minecraft.world.item.Items 'registerItem|static .*Item register'
p net.minecraft.core.Registry 'static .*register'
p net.minecraft.resources.ResourceKey 'create'
p net.minecraft.core.registries.Registries ' ITEM;'
p net.minecraft.world.item.CreativeModeTabs 'COMBAT'
p net.minecraft.world.item.component.CustomData 'public'
p net.minecraft.nbt.CompoundTag 'getInt|putInt|getBoolean|putBoolean|getLong|putLong'
p net.minecraft.core.component.DataComponents 'CUSTOM_DATA|CUSTOM_NAME|ITEM_NAME|ENCHANTMENT_GLINT|MAX_STACK_SIZE|UNBREAKABLE'
p net.minecraft.world.level.Level 'playSound\(|getGameTime|clip\('
p net.minecraft.world.level.BlockGetter 'clip\('
p net.minecraft.world.level.ClipContext '<init>|public net'
p net.minecraft.world.phys.AABB 'clip\(|expandTowards|inflate\('
p net.minecraft.world.entity.Entity 'invulnerableTime|getEyePosition|getLookAngle|getViewVector|damageSources|hurtServer'
p net.minecraft.world.entity.LivingEntity 'hurtServer|getMainHandItem|getItemInHand'
p net.minecraft.world.damagesource.DamageSources 'playerAttack|explosion|mobProjectile'
p net.minecraft.sounds.SoundEvents ' CROSSBOW_SHOOT| GENERIC_EXPLODE| FIREWORK_ROCKET_LAUNCH| IRON_GOLEM_HURT| ARMOR_EQUIP_IRON| ITEM_BREAK| NOTE_BLOCK_HAT| DISPENSER_FAIL| ANVIL_USE| FIREWORK_ROCKET_BLAST'
p net.minecraft.world.entity.player.Inventory 'clearContent|getContainerSize|setItem|getItem\(|getSelected|selected|add\('
p net.minecraft.world.entity.player.Player 'getMainHandItem|getInventory'
p net.minecraft.client.Options 'keyUse|keyAttack'
p net.minecraft.client.KeyMapping '<init>|public net|isDown|consumeClick|Category'
p 'net.minecraft.client.KeyMapping$Category' 'public'
p net.minecraft.client.Minecraft ' screen;|player;'
p com.mojang.blaze3d.platform.InputConstants 'KEY_R|Type'
p net.minecraft.world.item.ItemStack 'getOrDefault|set\(|get\(|isEmpty|getItem\(|copy\(|getHoverName'
p net.minecraft.network.codec.StreamCodec ' unit\('
for c in $(echo "$CP" | tr ':' '\n' | grep -i fabric); do unzip -l "$c" 2>/dev/null | awk '{print $4}' | grep -iE 'api/.*(ItemGroup|CreativeModeTab|KeyBinding|KeyMapping|ClientTickEvents|ServerPlayNetworking)[A-Za-z]*\.class$'; done | sort -u
p net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents 'public'
p net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents 'public'
p 'net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents$ModifyEntries' 'public'
p 'net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents$ModifyOutput' 'public'
p net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper 'public'
p net.fabricmc.fabric.api.client.keymapping.v1.KeyMappingHelper 'public'
p net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents 'END_CLIENT_TICK'
p net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking 'registerGlobalReceiver'
p 'net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking$Context' 'public'
p net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking ' send\('
